package simpopulation;

/**
 * Interface for the model of a living organism, which can replicate, reproduce and mutate.
 * Its fitness in its environment can be computed or compared.
 * 
 * @author group16
 *
 * @param <T> generic type for the organism implementation
 */
public interface Organism<T> {
    
    /**
     * Creates a replica of this organism.
     * 
     * @return organism of the same type
     */
    T replicate();
    
    /**
     * Returns an organism generated by the reproduction of this one.
     * 
     * @return organism of the same type
     */
    T reproduce();
    
    /**
     * Mutates this organism.
     */
    void mutate();
    
    /**
     * Compares the fitness of this organism with other of the same type.
     * @param other the organism to compare to
     * @return result of the comparison
     */
    boolean isFitter(T other);
    
    /**
     * Returns the fitness of this organism.
     * @return fitness value
     */
    double getFitness();
    
}
